# Generated by Django 3.1.7 on 2021-05-17 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20210426_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 59, 58, 240350), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 59, 58, 240350), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 13, 59, 58, 240350), verbose_name='添加时间'),
        ),
    ]
