# Generated by Django 3.1.7 on 2021-05-26 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20210521_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='是否金牌'),
        ),
        migrations.AlterField(
            model_name='city',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 27, 40, 613780), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 27, 40, 613780), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 27, 40, 613780), verbose_name='添加时间'),
        ),
    ]
