# Generated by Django 3.1.7 on 2021-05-27 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20210526_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 16, 46, 28, 75492), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 16, 46, 28, 75492), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 16, 46, 28, 75492), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 16, 46, 28, 75492), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 16, 46, 28, 75492), verbose_name='添加时间'),
        ),
    ]
