# Generated by Django 3.1.7 on 2021-05-27 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210527_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 6, 55, 514756), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 6, 55, 514756), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='coursetag',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 6, 55, 514756), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 6, 55, 514756), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 17, 6, 55, 514756), verbose_name='添加时间'),
        ),
    ]
