# Generated by Django 3.1.7 on 2021-04-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_image',
            field=models.ImageField(default='head_image/default.jpg', upload_to='head_image/%Y/%M', verbose_name='用户头像'),
        ),
    ]
