# Generated by Django 3.1.7 on 2021-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210426_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_image',
            field=models.ImageField(default='head_image/default.jpg', upload_to='head_image/%Y/%m', verbose_name='用户头像'),
        ),
    ]
