# Generated by Django 3.1.7 on 2021-05-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210527_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='head_image',
            field=models.ImageField(upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
    ]
